#!/bin/bash
intltool-update ar
intltool-update as
intltool-update bg
intltool-update bn_IN
intltool-update bn
intltool-update br
intltool-update bs
intltool-update ca
intltool-update cs
intltool-update cy
intltool-update da
intltool-update de
intltool-update el
intltool-update en_GB
intltool-update es
intltool-update et
intltool-update fa
intltool-update fi
intltool-update fr
intltool-update gu
intltool-update he
intltool-update hi
intltool-update hr
intltool-update hu
intltool-update id
intltool-update is
intltool-update it
intltool-update ja
intltool-update kn
intltool-update ko
intltool-update lt
intltool-update lv
intltool-update mai
intltool-update ml
intltool-update mr
intltool-update ms
intltool-update nb
intltool-update nds
intltool-update nl
intltool-update nn
intltool-update or
intltool-update pa
intltool-update pl
intltool-update pt_BR
intltool-update pt
intltool-update ro
intltool-update ru
intltool-update si
intltool-update sk
intltool-update sl
intltool-update sr@latin
intltool-update sr
intltool-update sv
intltool-update ta
intltool-update te
intltool-update th
intltool-update tr
intltool-update uk
intltool-update vi
intltool-update zh_CN
intltool-update zh_TW
